# Generated by Django 4.2.4 on 2023-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_task_author_task_created_at_task_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="author",
            new_name="created_by",
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
